import { KeyType } from "@/lib/types/key";

// @ts-ignore
export const keys: KeyType[][] = [
  [
    {
      keyCode: "escape",
      label: "esc",
      secondaryKeyCode: "",
      secondaryLabel: "",
      finger: "left",
    },
    {
      keyCode: "2",
      label: "1",
      secondaryKeyCode: "!",
      secondaryLabel: "!",
      fingerGroup: 5,
      finger: "left",
    },
    {
      keyCode: "2",
      label: "2",
      secondaryKeyCode: '"',
      secondaryLabel: '"',
      fingerGroup: 4,
      finger: "left",
    },
    {
      keyCode: "3",
      label: "3",
      secondaryKeyCode: "#",
      secondaryLabel: "#",
      fingerGroup: 3,
      finger: "left",
    },
    {
      keyCode: "4",
      label: "4",
      secondaryKeyCode: "$",
      secondaryLabel: "$",
      fingerGroup: 2,
      finger: "left",
    },
    {
      keyCode: "5",
      label: "5",
      secondaryKeyCode: "%",
      secondaryLabel: "%",
      fingerGroup: 2,
      finger: "left",
    },
    {
      keyCode: "6",
      label: "6",
      secondaryKeyCode: "&",
      secondaryLabel: "&",
      fingerGroup: 2,
      finger: "right",
    },
    {
      keyCode: "7",
      label: "7",
      secondaryKeyCode: "/",
      secondaryLabel: "/",
      fingerGroup: 2,
      finger: "right",
    },
    {
      keyCode: "8",
      label: "8",
      secondaryKeyCode: "(",
      secondaryLabel: "(",
      fingerGroup: 3,
      finger: "right",
    },
    {
      keyCode: "9",
      label: "9",
      secondaryKeyCode: ")",
      secondaryLabel: ")",
      fingerGroup: 4,
      finger: "right",
    },
    {
      keyCode: "0",
      label: "0",
      secondaryKeyCode: "=",
      secondaryLabel: "=",
      fingerGroup: 5,
      finger: "right",
    },
    {
      keyCode: "+",
      label: "+",
      secondaryKeyCode: "?",
      secondaryLabel: "?",
      fingerGroup: 5,
      finger: "right",
    },
    {
      keyCode: "equal",
      label: "´",
      secondaryKeyCode: "`",
      secondaryLabel: "`",
      fingerGroup: 5,
      finger: "right",
    },
    {
      keyCode: "backspace",
      label: "backspace",
      fingerGroup: 5,
      finger: "right",
      fromKey: "l",
      width: 2,
    },
  ],
  [
    {
      keyCode: "tab",
      label: "tab",
      fingerGroup: 5,
      finger: "left",
      width: 1.5,
    },
    { keyCode: "q", label: "q", fingerGroup: 5, finger: "left" },
    { keyCode: "w", label: "w", fingerGroup: 4, finger: "left" },
    { keyCode: "e", label: "e", fingerGroup: 3, finger: "left" },
    { keyCode: "r", label: "r", fingerGroup: 2, finger: "left" },
    { keyCode: "t", label: "t", fingerGroup: 2, finger: "left" },
    { keyCode: "y", label: "y", fingerGroup: 2, finger: "right" },
    { keyCode: "u", label: "u", fingerGroup: 2, finger: "right" },
    { keyCode: "i", label: "i", fingerGroup: 3, finger: "right" },
    { keyCode: "o", label: "o", fingerGroup: 4, finger: "right" },
    { keyCode: "p", label: "p", fingerGroup: 5, finger: "right" },
    { keyCode: "å", label: "å", fingerGroup: 5, finger: "right" },
    {
      keyCode: "bracketright",
      label: "¨",
      secondaryKeyCode: "^",
      secondaryLabel: "^",
      fingerGroup: 5,
      finger: "right",
    },
  ],
  [
    {
      label: "caps lock",
      keyCode: "caps lock",
      fingerGroup: 5,
      finger: "left",
      width: 1.75,
    },
    { keyCode: "a", label: "a", fingerGroup: 5, finger: "left" },
    { keyCode: "s", label: "s", fingerGroup: 4, finger: "left" },
    { keyCode: "d", label: "d", fingerGroup: 3, finger: "left" },
    { keyCode: "f", label: "f", fingerGroup: 2, finger: "left" },
    { keyCode: "g", label: "g", fingerGroup: 2, finger: "left" },
    { keyCode: "h", label: "h", fingerGroup: 2, finger: "right" },
    { keyCode: "j", label: "j", fingerGroup: 2, finger: "right" },
    { keyCode: "k", label: "k", fingerGroup: 3, finger: "right" },
    { keyCode: "l", label: "l", fingerGroup: 4, finger: "right" },
    { keyCode: "ø", label: "ø", fingerGroup: 5, finger: "right" },
    { keyCode: "æ", label: "æ", fingerGroup: 5, finger: "right" },
    {
      keyCode: "@",
      label: "@",
      secondaryKeyCode: "*",
      secondaryLabel: "*",
      fingerGroup: 5,
      finger: "right",
    },
  ],
  [
    {
      keyCode: "shiftleft",
      label: "shift",
      fingerGroup: 5,
      finger: "left",
      width: 1.25,
    },
    {
      keyCode: "<",
      label: "<",
      secondaryKeyCode: ">",
      secondaryLabel: ">",
      fingerGroup: 5,
      finger: "left",
    },
    { keyCode: "z", label: "z", fingerGroup: 4, finger: "left" },
    { keyCode: "x", label: "x", fingerGroup: 3, finger: "left" },
    { keyCode: "c", label: "c", fingerGroup: 2, finger: "left" },
    { keyCode: "v", label: "v", fingerGroup: 2, finger: "left" },
    { keyCode: "b", label: "b", fingerGroup: 2, finger: "right" },
    { keyCode: "n", label: "n", fingerGroup: 2, finger: "right" },
    { keyCode: "m", label: "m", fingerGroup: 3, finger: "right" },
    {
      keyCode: ",",
      label: ",",
      secondaryKeyCode: ";",
      secondaryLabel: ";",
      fingerGroup: 4,
      finger: "right",
    },
    {
      keyCode: ".",
      label: ".",
      secondaryKeyCode: ":",
      secondaryLabel: ":",
      fingerGroup: 5,
      finger: "right",
    },
    {
      keyCode: "-",
      label: "-",
      secondaryKeyCode: "_",
      secondaryLabel: "_",
      fingerGroup: 5,
      finger: "right",
    },
    {
      label: "shift",
      keyCode: "shiftright",
      fingerGroup: 5,
      finger: "right",
      width: 1.75,
    },
    {
      keyCode: "arrowup",
      label: "↑",
      fingerGroup: 5,
      finger: "right",
    },
  ],
  [
    {
      keyCode: "controlleft",
      label: "Ctrl",
      fingerGroup: 5,
      finger: "right",
      width: 1.25,
    },
    {
      keyCode: "altleft",
      label: "option",
      finger: "right",
      fingerGroup: 4,
      width: 1.25,
    },
    {
      keyCode: "metaleft",
      label: "command",
      finger: "right",
      width: 1.25,
      fingerGroup: 3,
    },
    {
      keyCode: " ",
      secondaryKeyCode: "space",
      label: "space",
      finger: "right",
      width: 10,
    },
    { label: "", keyCode: "", finger: "right", fingerGroup: 3 },
    { keyCode: "fn1", label: "fn1", finger: "right", fingerGroup: 4 },
    { keyCode: "fn3", label: "fn3", finger: "right", fingerGroup: 5 },
    { keyCode: "arrowleft", label: "←", fingerGroup: 5, finger: "right" },
    { keyCode: "arrowdown", label: "↓", fingerGroup: 5, finger: "right" },
    { keyCode: "arrowright", label: "→", fingerGroup: 5, finger: "right" },
  ],
].map((row) =>
  row.map((key) => ({
    ...key,
    fromKey: (() => {
      if (key.finger === "right") {
        return {
          5: "ø",
          4: "l",
          3: "k",
          2: "j",
        }[key.fingerGroup ?? 0];
      } else {
        return {
          5: "a",
          4: "s",
          3: "d",
          2: "f",
        }[key.fingerGroup ?? 0];
      }
    })(),
  })),
);
